### ISSUE TITLE
alternative positions in PDBs

### ISSUE THREAD

**Issue by andreashlarsen** [AUSAXS/AUSAXS#103]
are alternative positions taken into account, e.g. C-alpha in lyz172 in pdb 6z6u (e.g. by ignoring one of them)?

**Comment by klytje** [comment]
All atoms listed in the PDB file are used, though their contributions are scaled by the "Occupancy" field value. AFAIK alternate positions usually set this field to some percentage indicating the probability of the position, in which case they _are_ accounted for.
