### ISSUE TITLE
saxs_fitter litters $workdir/temp/ directory and other issues

### ISSUE THREAD

**Issue by franke-biosaxs** [AUSAXS/AUSAXS#107]
After a successful run, the "temp" directory is not removed. It should be if indeed it is a temporary directory.
Even better, use an actual temporary directory in the platform $TEMP directory. 

Additional observation: 
1. run saxs_fitter
2. CTRL+C during download
3. re-run saxs_fitter

It will fail in step 3 as some files were not downloaded in step 1, but it assumes that all should be there.

This will particular affect execution if saxs_fitter is executed multiple times in parallel in the same directory:
- first process starts, starts downloading
- second process starts and fails as the first is not yet done downloading

```
% bin/saxs_fitter 6lyz.pdb lyzexp.dat
Running AUSAXS v1.0.3
Reading PDB file from "./6lyz.pdb"
	Successfully read 1102 atomic records.
		101 of these are hydration atoms.
Unknown residue: "LYS". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/LYS.cif to temp/residues/LYS.cif
Unknown residue: "VAL". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/VAL.cif to temp/residues/VAL.cif
Unknown residue: "PHE". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/PHE.cif to temp/residues/PHE.cif
Unknown residue: "GLY". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/GLY.cif to temp/residues/GLY.cif
Unknown residue: "ARG". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ARG.cif to temp/residues/ARG.cif
Unknown residue: "CYS". Attempting to download specification.
^C
biosaxs@Daniels-MacBook-Pro-2 build % bin/saxs_fitter 6lyz.pdb lyzexp.dat
Running AUSAXS v1.0.3
Reading PDB file from "./6lyz.pdb"
	Successfully read 1102 atomic records.
		101 of these are hydration atoms.
Unknown residue: "CYS". Attempting to download specification.
	Residue CYS is already downloaded, but not present in the master list. 
	The file will now be parsed and re-added to the master file.
Could not find atom or bond section in file "temp/residues/CYS.cif"
libc++abi: terminating due to uncaught exception of type std::exception: std::exception
```

**Comment by klytje** [comment]
Ouch - you're really testing the limits of my application there! I never considered users corrupting the files in the `temp` folder this way :) 

Regarding the folder itself - I call it `temp` since it stores files which can safely be removed by the users, since they'll simply be recreated if missing. Using the platform-specific `$TEMP` folder is probably a better idea. I didn't do that yet since it requires OS-specific code, which I have tried my best to avoid so far. Mainly because I don't own a Mac to test it on haha.

**Comment by franke-biosaxs** [comment]
> Ouch - you're really testing the limits of my application there! I never considered users corrupting the files in the `temp` folder this way :)

Been there. Done that. I encountered all these issues the hard way myself when developing for ATSAS. A mental question of "who would ever do that?" usually is answered by: "about the second person ever to use the program". There is a world of difference between writing a one-off tool for oneself and an application meant for general consumption.

**Comment by klytje** [comment]
The specification files will now be redownloaded once if they cannot be parsed, which should solve this issue for good. It is still possible to corrupt the master file, though that should only be possible if the program is immediately closed upon startup, when the file is still being generated. I don't see any way to easily safeguard against that, so I'll leave it in for now. 

I'll leave the issue open for the `temp` folder issue.
