### ISSUE TITLE
saxs_fitter .fit output format is surprising

### ISSUE THREAD

**Issue by franke-biosaxs** [AUSAXS/AUSAXS#108]
The following completed sucessfully:
```
% bin/saxs_fitter 6lyz.pdb lyzexp.dat
```
The reported chi^2 is similar to that reported by crysol. However, after looking at the accompanying  fit in primus, it looks very odd and the calculated chi-square of the .fit is different to the value reported. Took me some time to figure out: the .fit file has five columns, where the residuals column is unexpected by ATSAS tools. Removing that fifth column fixes the plot and chi-square calculation in primus.

Potential users are likely to what I did and they will be as confused as I was. One may now discuss whether this is an ATSAS issue, simply assuming file formats given an extension, or something that should be addressed by saxs_fitter.

<img width="612" alt="Screenshot 2024-11-05 at 16 25 48" src="https://github.com/user-attachments/assets/971a7acf-27d9-4d5a-8ee2-3ab1371931ef">

**Comment by klytje** [comment]
Noted. I will fix this to be consistent with the ATSAS tools. Thank you for the report.
