### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by andreashlarsen** [AUSAXS/AUSAXS#59]
Hi, 

I would like to try the program, but how do I do? I am working on macos, so I downloaded the binaries, and tried ./saxs_fitter, but this did not work - could you provide a simple guide to how to run a fit using the program, and maybe provide some example data for a minimal run? 

best regards, Andreas

**Comment by klytje** [comment]
Hi @andreashlarsen! I think you're my first real user!

I am limited in the help I can provide for MacOS since I don't own such a system myself to test on (hopefully this will change soon!). I think it should be functional however. 

Have you already read the [docs](https://github.com/AUSAXS/AUSAXS/wiki/SAXS-fitter)? I'll update it to be more recent later today. I've also just [uploaded a new version](https://github.com/AUSAXS/AUSAXS/releases/tag/v1.0.3) of the program you should download to match the docs. 

The most basic usage is `saxs_fitter <pdb file> <data file>`, which uses our (unpublished) in-house method for the excluded volume. Typically this works just fine. 

We've also implemented the CRYSOL excluded volume method, available by supplying the `--hm hmmtffx --fit-excluded-volume` arguments. 

A third approach is to use our experimental grid-based approximation, available with `--hm hmmtffgs --fit-excluded-volume` arguments. 

The SAXS fitting program is still in active development, so many of these arguments will likely be changed to something a bit more user-friendly in the near future. A complete description of all available methods will be given in an upcoming article, though I'm happy to answer any questions you may have here.

**Comment by klytje** [comment]
You can try it with this lysozyme data I have lying around in my working directory. 
[2epe.zip](https://github.com/user-attachments/files/16053276/2epe.zip)

Extract the data, and run the program like so: `saxs_fitter 2epe.dat 2epe.pdb`

**Comment by andreashlarsen** [comment]
okay, thanks... in some steps I could run the program: 
```
cd to dir
chmod +x saxs_fitter
```
then right-click and open (to open although it is from non-verified source) 

then I could run with: 
```
./saxs_fitter 2epe.dat 2epe.pdb
```
(I placed your example files in the same dir as saxs_fitter executable)

now I just need to understand the output: 
´´´
Running AUSAXS v1.0.3

Reading PDB file from "./2epe.pdb"
Unknown residue: "LYS". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/LYS.cif to temp/residues/LYS.cif
Unknown residue: "VAL". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/VAL.cif to temp/residues/VAL.cif
Unknown residue: "PHE". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/PHE.cif to temp/residues/PHE.cif
Unknown residue: "GLY". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/GLY.cif to temp/residues/GLY.cif
Unknown residue: "ARG". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ARG.cif to temp/residues/ARG.cif
Unknown residue: "CYS". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/CYS.cif to temp/residues/CYS.cif
Unknown residue: "GLU". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/GLU.cif to temp/residues/GLU.cif
Unknown residue: "LEU". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/LEU.cif to temp/residues/LEU.cif
Unknown residue: "ALA". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ALA.cif to temp/residues/ALA.cif
Unknown residue: "MET". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/MET.cif to temp/residues/MET.cif
Unknown residue: "HIS". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/HIS.cif to temp/residues/HIS.cif
Unknown residue: "ASP". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ASP.cif to temp/residues/ASP.cif
Unknown residue: "ASN". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ASN.cif to temp/residues/ASN.cif
Unknown residue: "TYR". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/TYR.cif to temp/residues/TYR.cif
Unknown residue: "SER". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/SER.cif to temp/residues/SER.cif
Unknown residue: "TRP". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/TRP.cif to temp/residues/TRP.cif
Unknown residue: "THR". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/THR.cif to temp/residues/THR.cif
Unknown residue: "GLN". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/GLN.cif to temp/residues/GLN.cif
Unknown residue: "ILE". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/ILE.cif to temp/residues/ILE.cif
Unknown residue: "PRO". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/PRO.cif to temp/residues/PRO.cif
Unknown residue: "HOH". Attempting to download specification.
	Successfully downloaded files.rcsb.org/ligands/view/HOH.cif to temp/residues/HOH.cif
	Successfully read 1049 atomic records.
		48 of these are hydration atoms.
Total displaced charge: 5077.13
Added -5.07206 electrons to each atom (N: 1001).

Reading dataset from "./2epe.dat"
	4 columns detected. Assuming the format is [q | I | Ierr | qerr]
	Successfully read 104 data points from ./2epe.dat
+----------------------------------------------------------+
|                       FIT REPORT                         |
+----------------------------------------------------------+
| Converged: yes                              Fevals: 32   |
| chi2: 122.103      dof: 100       chi2/dof: 1.22103      |
+----------------------------------------------------------+
| PAR      | VAL          | UNC          |                 |
| c        | 0.164409     | 0            |                 |
| a        | 1.12537e-09  | 3.24223e-12  |                 |
| b        | 8.59958e-05  | 5.13189e-06  |                 |
+----------------------------------------------------------+
RhoM is 1.5654 g/cm³
Output written to file output/saxs_fitter/2epe/model.pdb.
´´´
but the fit looks fine... 

And the output files: 
´´´
report.txt
p(r).png.plot
profiles.png.plot
ausaxs.fit
2epe.scat
model.pdb
´´´
Most are self-explanatory. But how to open the .plot files? 
I tried with gnuplot: 
´´´
brew install gnuplot
gnuplot profiles.png.plot
´´´
but this did not work:
´´´
PlotHistogram
^
"profiles.png.plot" line 1: invalid command
´´´
anyways, all the above seems to be the same as can be done with crysol or pepsi-saxs (or similar). Can you provide an example of EM validation - to me that is the most interesting new feature of AUSAXS (and also the subject of your [paper](https://journals.iucr.org/d/issues/2024/07/00/wan5003/index.html)

**Comment by klytje** [comment]
> But how to open the .plot files? I tried with gnuplot (had to install first):

The `.plot` is a custom format to be used with my plotting script, which should be shipped along with the binary. Simply invoke it with Python like so: `python plot.py` in the folder with the plot files. 

I added those as an option for easily making nicer plots. If you want to customize them, you should be able to import the `.scat` and `.fit` files into `CRYSOL`s plotting tool as well. 

> anyways, all the above seems to be the same as can be done with crysol or pepsi-saxs (or similar).

More or less, though I am quite skeptical of their programs. This will be detailed in an upcoming article, hopefully to be published within the coming months. 

> Can you provide an example of EM validation - to me that is the most interesting new feature of AUSAXS

See the user guide [here](https://github.com/AUSAXS/AUSAXS/wiki/Validation-of-EM-maps). 

To use it, you will need an EM map in either the `MRC`, `CCP4`, or `MAP` format, and the accompanying SAXS data. Using one of the examples from the article, you can download the [SASDJG5](https://www.sasbdb.org/data/SASDJG5/) SAXS data and use it with the [EMD24889](https://www.ebi.ac.uk/emdb/EMD-24889) map data. Then you can invoke the program exactly like you did with the SAXS fitter: 

`em_fitter <SASDJG5 data path> <EMD24889 map path>`

There's a few different options available; see the user guide for information on those. The most important is probably the `--frequency X` option, which will skip every Xth voxel of the EM map in each direction. Thus it speeds up the calculation by a factor $X^3$, which can be nice for getting a quick estimate of the fit quality.

**Comment by andreashlarsen** [comment]
okay, thanks. Plotting works python plot.py from the bin folder, or from the output folder:
```
python ../../../plot.py
```
which generates nice-looking plots. 
also, the em example worked fine after making the file executable
```
chmod +x em_fitter
```
hope to use it the program at some point - it seems really useful to not have to use the atomic model, but being able to use the electron density directly... cheers.

**Comment by klytje** [comment]
Perfect - thanks for testing it out!
